[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m playwright install --with-deps chromium"
]

[phases.build]
cmds = [
  "python --version",
  "pip list"
]

[start]
cmd = "Bash Terminal start.sh"
