[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate && pip install --upgrade pip",
  "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python --version",
  "source /opt/venv/bin/activate && pip list"
]

[start]
cmd = "python -m uvicorn api_server:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300"

[variables]
PATH = "/opt/venv/bin:$PATH"
PYTHONPATH = "/app:$PYTHONPATH"
