
[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt',
  'python -m playwright install --with-deps chromium'
]

[phases.build]
cmds = ['python --version', 'pip list']

[start]
cmd = 'uvicorn api_server:app --host 0.0.0.0 --port $PORT'
