[providers.python]
usePoetry = false

[phases.setup]
nixPkgs = ['python311', 'pip']
aptPkgs = ['libgobject-2.0-0', 'libdbus-glib-1-2', 'libgtk-3-0']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt',
  'python -m playwright install --with-deps chromium'
]

[phases.build]
cmds = ['python --version', 'pip list']

[start]
cmd = 'bash start.sh'

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/opt/playwright"
