[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate && pip install --upgrade pip",
  "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python --version",
  "source /opt/venv/bin/activate && pip list"
]

[start]
cmd = "bash start.sh"

[variables]
PATH = "/opt/venv/bin:$PATH"
