[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.venv"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt", 
  "python -m playwright install --with-deps chromium"
]

[phases.build]
cmds = [
  "python --version",
  "pip --version",
  "pip list"
]

[start]
cmd = "bash start.sh"
