[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
