[build]
builder = "NIXPACKS"

[deploy]
startCommand = "PYTHONPATH=/app:$PYTHONPATH python -m uvicorn api_server:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
