
# Anti-Aging Medicine Specialty Scoring Configuration
# Production Rebuild V4.0 - Optimized for Membership Models

# Score Thresholds
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  # Core Specialty Match (20 points)
  specialty_match:
    anti_aging_practice: 20
    longevity_medicine: 18
    age_management: 18
  
  # Business Model (20 points)
  decision_autonomy:
    membership_model: 20
    concierge_model: 15
    independent_ownership: 10
  
  # Service Offerings (25 points)
  aesthetic_services:
    hormone_therapy: 10
    iv_therapy: 6
    aesthetic_procedures: 6
    peptide_therapy: 3
  
  # Reviews & Rating (10 points)
  reviews_rating:
    rating_4_5_plus: 5
    rating_4_0_to_4_5: 3
    review_count_50_plus: 5
    review_count_20_to_50: 3
  
  # Digital Presence (10 points)
  digital_presence:
    has_website: 5
    educational_content: 3
    active_social_media: 2
  
  # Wellness Focus (10 points)
  wellness_focus:
    functional_medicine: 5
    integrative_health: 3
    preventive_focus: 2
  
  # Premium Positioning (5 points)
  financial_indicators:
    premium_services: 3
    membership_revenue: 2

# Data Quality Adjustments
data_quality_multipliers:
  limited_data_boost:
    specialty_match: 1.3
    decision_autonomy: 1.5
    reviews_rating: 1.4
  
  rich_data_boost:
    aesthetic_services: 1.0
    wellness_focus: 1.0

# High-Value Keywords
high_value_keywords:
  - "anti-aging"
  - "longevity"
  - "hormone optimization"
  - "peptide therapy"
  - "iv therapy"
  - "functional medicine"
  - "age management"
  
  keyword_bonus: 3
  max_keyword_bonus: 15

# Special Rules
special_rules:
  # Boost membership-based practices
  membership_boost:
    enabled: true
    boost_amount: 12
  
  # Boost hormone/peptide therapy providers
  advanced_therapy_boost:
    enabled: true
    keywords: ["hormone", "peptide", "bioidentical"]
    boost_amount: 10
