# Anti-Aging Medicine Specialty Scoring Configuration
# Production Rebuild V4.0 - Optimized for Membership Models

# Score Thresholds
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  specialty_match:
    anti_aging_practice: 20
    longevity_medicine: 18
    age_management: 15

  services_offered:
    hormone_therapy: 5
    peptides: 5
    regenerative_therapies: 5
    iv_therapy: 5
    stem_cell: 5

  legitimacy_indicators:
    board_certified: 10
    fellowship_trained: 8
    years_experience_10_plus: 5

  reviews_rating:
    rating_4_5_plus: 5
    review_count_50_plus: 5

  digital_presence:
    has_website: 5
    instagram_found: 4
    patient_testimonials: 3

  high_value_keywords:
    - "hormone replacement therapy"
    - "peptides"
    - "anti-aging medicine"
    - "stem cells"
    - "age reversal"
    - "longevity clinic"

keyword_bonus: 2
max_keyword_bonus: 10
