
# Dermatology Specialty Scoring Configuration
# Production Rebuild V4.0 - Adjusted for Limited Data Scenarios

# Score Thresholds (Adaptive based on data completeness)
thresholds:
  # Standard thresholds (100% data available)
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  # Adjusted for limited data (40-75% data available)
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  # Minimum thresholds (<40% data available)
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  # Core Specialty Match (20 points)
  specialty_match:
    dermatology_practice: 20
    cosmetic_dermatology: 15
    medical_dermatology: 10
  
  # Decision Autonomy (15 points)
  decision_autonomy:
    solo_practitioner: 10
    independent_ownership: 10
    not_hospital_affiliated: 10
    small_practice: 5
  
  # Aesthetic Services (25 points)
  aesthetic_services:
    injectables: 8
    laser_treatments: 8
    skin_rejuvenation: 6
    body_contouring: 3
  
  # Reviews & Rating (10 points)
  reviews_rating:
    rating_4_5_plus: 5
    rating_4_0_to_4_5: 3
    review_count_50_plus: 5
    review_count_20_to_50: 3
  
  # Digital Presence (10 points)
  digital_presence:
    has_website: 5
    active_instagram: 3
    active_facebook: 2
  
  # Service Variety (10 points)
  service_variety:
    per_service: 2
    max_points: 10
  
  # Financial Indicators (10 points)
  financial_indicators:
    cashpay_focus: 5
    premium_positioning: 3
    membership_model: 2

# Data Quality Adjustments
data_quality_multipliers:
  # When data is limited, boost these scores
  limited_data_boost:
    specialty_match: 1.3
    reviews_rating: 1.5
    digital_presence: 1.2
  
  # When data is rich, standard scoring
  rich_data_boost:
    aesthetic_services: 1.0
    service_variety: 1.0

# High-Value Keywords (Bonus Points)
high_value_keywords:
  - "botox"
  - "filler"
  - "laser"
  - "coolsculpting"
  - "microneedling"
  - "aesthetic dermatology"
  - "cosmetic procedures"
  
  keyword_bonus: 2  # Points per keyword found
  max_keyword_bonus: 10
