# Family Practice Specialty Scoring Configuration
# Production Rebuild V4.0 - Optimized for DPC/Concierge Models

# Score Thresholds
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  specialty_match:
    family_practice: 20
    primary_care: 18
    internal_medicine: 15

  business_model:
    concierge: 10
    membership_based: 10
    dpc: 10

  services:
    same_day_visit: 5
    chronic_condition: 5
    telemedicine: 3

  reviews_rating:
    rating_4_5_plus: 5
    review_count_50_plus: 5

  digital_presence:
    has_website: 5
    patient_portal: 4
    instagram_found: 3

  high_value_keywords:
    - "direct primary care"
    - "membership medicine"
    - "family physician"
    - "concierge doctor"
    - "annual wellness"
    - "chronic condition"

keyword_bonus: 2
max_keyword_bonus: 10
