
# Family Practice Specialty Scoring Configuration
# Production Rebuild V4.0 - Optimized for DPC/Concierge Models

# Score Thresholds
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  # Core Specialty Match (20 points)
  specialty_match:
    family_practice: 20
    primary_care: 18
    internal_medicine: 15
  
  # Business Model (25 points - CRITICAL for FP)
  decision_autonomy:
    dpc_model: 20  # Direct Primary Care
    concierge_model: 20
    independent_ownership: 10
    membership_based: 15
  
  # Aesthetic/Wellness Services (20 points)
  aesthetic_services:
    aesthetic_procedures: 10
    weight_loss_services: 6
    hormone_therapy: 6
    iv_therapy: 4
  
  # Reviews & Rating (10 points)
  reviews_rating:
    rating_4_5_plus: 5
    rating_4_0_to_4_5: 3
    review_count_50_plus: 5
    review_count_20_to_50: 3
  
  # Digital Presence (10 points)
  digital_presence:
    has_website: 5
    active_social_media: 3
    online_scheduling: 2
  
  # Wellness Focus (10 points)
  wellness_focus:
    functional_medicine: 5
    integrative_health: 3
    preventive_care: 2
  
  # Financial Model (5 points)
  financial_indicators:
    membership_revenue: 3
    cashpay_services: 2

# Data Quality Adjustments
data_quality_multipliers:
  limited_data_boost:
    specialty_match: 1.3
    decision_autonomy: 1.5
    reviews_rating: 1.4
  
  rich_data_boost:
    aesthetic_services: 1.0
    wellness_focus: 1.0

# High-Value Keywords
high_value_keywords:
  - "direct primary care"
  - "dpc"
  - "concierge medicine"
  - "membership"
  - "functional medicine"
  - "aesthetic procedures"
  - "weight loss"
  
  keyword_bonus: 3
  max_keyword_bonus: 15

# Special Rules
special_rules:
  # Heavily boost DPC/Concierge models
  dpc_boost:
    enabled: true
    boost_amount: 15
  
  # Penalize traditional insurance-based practices
  insurance_based_penalty:
    enabled: true
    keywords: ["accepts all insurance", "medicare", "medicaid"]
    penalty_amount: -10
