# Scoring Config Schema v4.1
# - version: numeric config version
# - specialty: slug for the vertical
# - thresholds: {standard|limited_data|min_data} -> {high_fit, medium_fit, low_fit}
# - weights: top-level categories with per-signal weights (positive or negative)
# - keyword_bonus: flat bonus per matched high-value keyword (capped by max_keyword_bonus)
# - data_completeness: fields that determine limited_data/min_data mode
# - special_rules: optional rules (boosts/penalties) with enable flags
# Notes:
# * All weights are additive; suggested sum of absolute values ~100.
# * No '...' end-of-document markers (they break YAML parsing).
# * Keep key names consistent across specialties.

version: 4.1
specialty: medspa
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0
data_completeness:
  required_fields:
  - name
  - address
  - phone
  nice_to_have:
  - website
  - domain
  - google_place_id
  - reviews_count
  - avg_rating
  - categories
  - services
  limited_threshold: 3
  minimum_threshold: 1
weights:
  specialty_match:
    category_contains:
      medical_spa: 18
      spa_medical: 16
      aesthetics_clinic: 10
    name_contains:
      medspa: 6
      aesthetics: 4
      wellness: 3
  ownership_model:
    physician_owned: 12
    injector_led: 8
    franchise: -12
    chain: -10
  services_offered:
    laser_hair_removal: 6
    ipl: 5
    skin_tightening: 6
    body_contouring: 6
    botox: 6
    fillers: 5
    hydrafacial: 4
    microneedling_rf: 7
  credibility_indicators:
    has_md_supervision: 8
    medical_director_listed: 6
    before_after_gallery: 4
  reviews_rating:
    avg_rating_gt_4_5: 8
    reviews_count_gt_120: 6
    recent_reviews_90d: 3
  digital_presence:
    has_website: 5
    online_booking: 6
    instagram_found: 4
    tiktok_found: 3
high_value_keywords:
- medical spa
- injectables
- RF microneedling
- skin tightening
- laser hair removal
keyword_bonus: 2
max_keyword_bonus: 10
special_rules:
  franchise_penalty:
    enabled: true
    keywords:
    - franchise
    - corporate
    - chain
    penalty_amount: -15
  physician_owned_boost:
    enabled: true
    boost_amount: 10
