
# MedSpa Specialty Scoring Configuration
# Production Rebuild V4.0 - Optimized for Independent Ownership

# Score Thresholds
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  # Core Specialty Match (20 points)
  specialty_match:
    medspa_practice: 20
    medical_spa: 18
    aesthetic_center: 15
  
  # Independent Ownership (20 points - CRITICAL)
  decision_autonomy:
    physician_owned: 15
    independent_ownership: 15
    medical_director: 10
    not_franchise: 10
  
  # Service Offerings (25 points)
  aesthetic_services:
    injectables: 8
    laser_treatments: 7
    body_contouring: 7
    advanced_technology: 3
  
  # Reviews & Rating (10 points)
  reviews_rating:
    rating_4_5_plus: 5
    rating_4_0_to_4_5: 3
    review_count_50_plus: 5
    review_count_20_to_50: 3
  
  # Digital Presence (10 points)
  digital_presence:
    has_website: 4
    active_instagram: 4
    online_booking: 2
  
  # Service Variety (10 points)
  service_variety:
    per_service: 2
    max_points: 10
  
  # Business Model (5 points)
  financial_indicators:
    membership_model: 3
    package_deals: 2

# Data Quality Adjustments
data_quality_multipliers:
  limited_data_boost:
    specialty_match: 1.3
    decision_autonomy: 1.5
    reviews_rating: 1.4
  
  rich_data_boost:
    aesthetic_services: 1.0
    service_variety: 1.0

# High-Value Keywords
high_value_keywords:
  - "medical spa"
  - "physician-owned"
  - "medical director"
  - "botox"
  - "coolsculpting"
  - "laser"
  - "body contouring"
  
  keyword_bonus: 2
  max_keyword_bonus: 10

# Special Rules
special_rules:
  # Penalize franchise indicators
  franchise_penalty:
    enabled: true
    keywords: ["franchise", "chain", "corporate"]
    penalty_amount: -15
  
  # Boost physician-owned medspas
  physician_owned_boost:
    enabled: true
    boost_amount: 10
