# OB/GYN Specialty Scoring Configuration
# Production Rebuild V4.0 - Optimized for Limited Data & Solo Practices

# Score Thresholds (Adaptive - MORE AGGRESSIVE for OB/GYN)
thresholds:
  standard:
    high_fit: 65  # Lower than other specialties
    medium_fit: 45  # Lower threshold
    low_fit: 0
  
  limited_data:
    high_fit: 45  # More forgiving for OB/GYN
    medium_fit: 30  # Catch more practices
    low_fit: 0
  
  minimum_data:
    high_fit: 35  # Very forgiving
    medium_fit: 20  # Capture solo or new OBs
    low_fit: 0

# Scoring Weights
weights:
  specialty_match:
    obgyn: 20
    women's_health: 18
    prenatal_care: 10

  services_offered:
    birth_control: 5
    hormone_therapy: 5
    menopause_support: 4
    pelvic_ultrasound: 3
    robotic_surgery: 3

  ownership_model:
    independent: 10
    solo_practice: 8
    not_affiliated: 6

  reviews_rating:
    rating_4_5_plus: 5
    review_count_50_plus: 4

  digital_presence:
    has_website: 5
    has_portal: 4
    instagram_found: 3
    facebook_found: 2

  high_value_keywords:
    - "gynecologist"
    - "obstetrician"
    - "pap smear"
    - "annual exam"
    - "pregnancy care"
    - "female doctor"

keyword_bonus: 2
max_keyword_bonus: 8
