
# Plastic Surgery Specialty Scoring Configuration
# Production Rebuild V4.0 - Adjusted for Limited Data Scenarios

# Score Thresholds (Adaptive based on data completeness)
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  # Core Specialty Match (20 points)
  specialty_match:
    plastic_surgery_practice: 20
    cosmetic_surgery: 18
    board_certified: 15
  
  # Decision Autonomy (15 points)
  decision_autonomy:
    solo_practitioner: 10
    independent_ownership: 10
    private_practice: 8
    not_hospital_affiliated: 10
  
  # Non-Surgical Focus (25 points)
  aesthetic_services:
    injectables: 8
    laser_treatments: 7
    body_contouring: 6
    skin_rejuvenation: 4
  
  # Reviews & Rating (10 points)
  reviews_rating:
    rating_4_5_plus: 5
    rating_4_0_to_4_5: 3
    review_count_50_plus: 5
    review_count_20_to_50: 3
  
  # Digital Presence (10 points)
  digital_presence:
    has_website: 5
    active_instagram: 3
    before_after_photos: 2
  
  # Service Variety (10 points)
  service_variety:
    per_service: 2
    max_points: 10
  
  # Financial Indicators (10 points)
  financial_indicators:
    premium_positioning: 5
    cashpay_focus: 3
    luxury_practice: 2

# Data Quality Adjustments
data_quality_multipliers:
  limited_data_boost:
    specialty_match: 1.3
    reviews_rating: 1.5
    board_certified: 1.4
  
  rich_data_boost:
    aesthetic_services: 1.0
    service_variety: 1.0

# High-Value Keywords
high_value_keywords:
  - "botox"
  - "filler"
  - "non-surgical"
  - "aesthetic"
  - "cosmetic procedures"
  - "body contouring"
  - "facial rejuvenation"
  
  keyword_bonus: 2
  max_keyword_bonus: 10
