
# Plastic Surgery Scoring Configuration
# Optimized for aesthetic/cosmetic plastic surgery practices
# Focus: High aesthetic focus, independent decision-making, strong digital presence

weights:
  aesthetic_indicators: 0.30        # Strong focus on cosmetic procedures
  independent_practice: 0.25        # Independent vs. hospital-affiliated
  digital_presence: 0.20            # Website quality and online engagement
  location_quality: 0.12            # Affluent area indicators
  practice_size: 0.08               # Small-to-medium preferred
  recency: 0.05                     # Recent activity signals

features:
  aesthetic_indicators:
    keywords:
      high_value:
        - cosmetic
        - aesthetic
        - beauty
        - rejuvenation
        - enhancement
        - anti-aging
        - facial
        - body contouring
        - breast augmentation
        - liposuction
        - rhinoplasty
        - facelift
        - botox
        - filler
        - non-surgical
      medium_value:
        - plastic surgery
        - reconstructive
        - skin care
        - laser
        - injectables
      negative:
        - insurance accepted
        - medicaid
        - emergency
        - trauma
        - hospital
        - burn unit
    weight_multiplier: 1.5
    
  independent_practice:
    practice_types:
      highly_preferred:
        - solo practitioner
        - private practice
        - independent
        - boutique
      preferred:
        - small group
        - partnership
        - associates
      avoid:
        - hospital
        - medical center
        - health system
        - corporate
        - chain
    scoring:
      solo: 100
      small_group: 85
      medium_group: 60
      hospital_affiliated: 20
      corporate: 10
      
  digital_presence:
    website_indicators:
      strong_signals:
        - before/after gallery
        - patient testimonials
        - procedure videos
        - virtual consultation
        - online booking
        - blog/resources
        - social media integration
        - professional photography
      medium_signals:
        - contact form
        - procedure descriptions
        - doctor bio
        - office photos
      quality_multipliers:
        has_gallery: 1.3
        has_testimonials: 1.2
        has_booking: 1.15
        
  location_quality:
    affluent_indicators:
      - upscale
      - luxury
      - private
      - exclusive
      - boutique
    area_type_scores:
      high_end_retail: 100
      affluent_residential: 95
      medical_plaza: 80
      downtown: 75
      suburban: 60
      rural: 30
      
  practice_size:
    optimal_indicators:
      - 1-3 surgeons
      - boutique
      - intimate
      - personalized
      - concierge
    size_scores:
      solo: 100
      2-3_surgeons: 95
      4-6_surgeons: 70
      7plus_surgeons: 40
      
  recency:
    activity_signals:
      - recently updated
      - new procedures
      - latest technology
      - recent reviews
      - active social media
    time_decay_months: 6

penalties:
  hospital_affiliation: -30
  insurance_focus: -25
  emergency_services: -35
  reconstructive_only: -20
  no_website: -40
  outdated_website: -20
  generic_stock_photos: -15

bonuses:
  aaas_member: 15              # American Academy of Aesthetic Surgery
  abps_certified: 20           # American Board of Plastic Surgery
  multiple_locations: 10
  med_spa_services: 15
  cash_only_practice: 25
  membership_program: 20
  has_app: 10

thresholds:
  minimum_score: 30
  good_prospect: 65
  excellent_prospect: 80
  
notes: |
  Plastic surgery practices are prime targets for aesthetic devices.
  Key success factors:
  - Independent decision-making authority
  - Strong aesthetic/cosmetic focus (vs. reconstructive)
  - High-end clientele willing to pay cash
  - Modern digital presence with visual content
  - Located in affluent areas
  - Not hospital-affiliated or insurance-dependent
