# Plastic Surgery Specialty Scoring Configuration
# Production Rebuild V4.0 - Adjusted for Limited Data Scenarios

# Score Thresholds (Adaptive based on data completeness)
thresholds:
  standard:
    high_fit: 70
    medium_fit: 50
    low_fit: 0
  
  limited_data:
    high_fit: 50
    medium_fit: 35
    low_fit: 0
  
  minimum_data:
    high_fit: 40
    medium_fit: 25
    low_fit: 0

# Scoring Weights
weights:
  specialty_match:
    plastic_surgery_practice: 20
    cosmetic_surgeon: 18
    reconstructive: 10

  services_offered:
    rhinoplasty: 5
    breast_augmentation: 5
    tummy_tuck: 5
    lipo: 5
    facial_rejuvenation: 5

  credibility_indicators:
    board_certified: 10
    years_experience_10_plus: 8
    before_after_gallery: 5

  reviews_rating:
    rating_4_5_plus: 5
    review_count_50_plus: 5

  digital_presence:
    has_website: 5
    instagram_found: 4
    youtube_channel: 3

  high_value_keywords:
    - "board certified"
    - "rhinoplasty"
    - "augmentation"
    - "cosmetic procedure"
    - "before and after photos"
    - "facial plastic surgery"

keyword_bonus: 2
max_keyword_bonus: 12
